"""SHA-256 digests of this release's PapyrusLinterCLI assets.

Generated by .github/scripts/write_cli_hashes.py; do not edit by hand.
"""

CLI_SHA256 = {
    'PapyrusLinterCLI-linux': 'd9f06240056c93a834de19d429b89305e7c78ec57aed8bd4a2d8c61cba3d8c34',
    'PapyrusLinterCLI-macos': '397be4eed842edc371b0bb2711752398847d5e7975eb7e813827732e780a1dc9',
    'PapyrusLinterCLI-windows.exe': '4f2803585c3264782f1490f39cb32b080aca831203ce97627ca46125321601c1',
}
