version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/app/src-tauri"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/crates/papyrus-parser"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/crates/papyrus-lints"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
