"""Bakes PapyrusLinterCLI and PapyrusLinter SHA-256 digests into the editor
plugins.

Extracted out of write_cli_hashes.py (which mixed this logic with its CLI
entrypoint) with no behavior change.

The plugins download the CLI that matches their own release tag, and they
also accept a user-supplied path to that same release's desktop-app binary.
The hashes of those binaries are only known after the `release` job
uploads them, so this is run in the plugin packaging jobs against the
just-built assets and rewrites the checked-in hash modules before vsce/zip
run.

Each asset key maps to a list of accepted SHA-256 digests: the official
CLI first, then the GUI binary when it was supplied. Downloads must match
the CLI digest; a user-supplied executable may match any digest in the
list.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

ASSETS = (
    "PapyrusLinterCLI-linux",
    "PapyrusLinterCLI-macos",
    "PapyrusLinterCLI-windows.exe",
)

# Optional desktop-app binaries accepted as a user-supplied executable
# for the corresponding CLI asset. Missing files are skipped so local
# test fixtures that only ship the CLI still work; the release workflow
# copies them into the asset directory before invoking this script.
GUI_ASSETS = {
    "PapyrusLinterCLI-linux": "PapyrusLinter-linux",
    "PapyrusLinterCLI-macos": "PapyrusLinter-macos",
    "PapyrusLinterCLI-windows.exe": "PapyrusLinter-windows.exe",
}

REPO_ROOT = Path(__file__).resolve().parents[2]
TS_PATH = REPO_ROOT / "vscode-extension" / "src" / "cliHashes.ts"
PY_PATH = REPO_ROOT / "SublimeLinter-contrib-papyrus-lint" / "cli_hashes.py"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def collect_hashes(asset_dir: Path) -> dict[str, list[str]]:
    hashes: dict[str, list[str]] = {}
    missing = []
    for asset in ASSETS:
        path = asset_dir / asset
        if not path.is_file():
            missing.append(asset)
            continue
        digests = [sha256_file(path)]
        gui = GUI_ASSETS.get(asset)
        if gui:
            gui_path = asset_dir / gui
            if gui_path.is_file():
                digests.append(sha256_file(gui_path))
        hashes[asset] = digests
    if missing:
        raise FileNotFoundError("missing CLI assets: " + ", ".join(missing))
    return hashes


def _digest_list(digests: list[str]) -> str:
    inner = ", ".join(f"'{digest}'" for digest in digests)
    return f"[{inner}]"


def render_ts(hashes: dict[str, list[str]]) -> str:
    entries = ",\n".join(
        f"  '{asset}': {_digest_list(hashes[asset])}" for asset in ASSETS
    )
    return (
        "/** SHA-256 digests of this release's PapyrusLinterCLI and PapyrusLinter assets.\n"
        " * Generated by .github/scripts/write_cli_hashes.py; do not edit by hand.\n"
        " * The first digest is the standalone CLI; later entries are accepted\n"
        " * alternatives (the desktop app) for a user-supplied executable.\n"
        " */\n"
        "export const CLI_SHA256: Record<string, readonly string[]> = {\n"
        f"{entries},\n"
        "};\n"
    )


def render_py(hashes: dict[str, list[str]]) -> str:
    entries = ",\n".join(
        f"    '{asset}': {_digest_list(hashes[asset])}" for asset in ASSETS
    )
    return (
        '"""SHA-256 digests of this release\'s PapyrusLinterCLI and PapyrusLinter assets.\n'
        "\n"
        "Generated by .github/scripts/write_cli_hashes.py; do not edit by hand.\n"
        "The first digest is the standalone CLI; later entries are accepted\n"
        "alternatives (the desktop app) for a user-supplied executable.\n"
        '"""\n'
        "\n"
        "CLI_SHA256 = {\n"
        f"{entries},\n"
        "}\n"
    )


def write_hashes(
    hashes: dict[str, list[str]], ts_path: Path = TS_PATH, py_path: Path = PY_PATH
) -> None:
    ts_path.parent.mkdir(parents=True, exist_ok=True)
    py_path.parent.mkdir(parents=True, exist_ok=True)
    ts_path.write_text(render_ts(hashes), encoding="utf-8")
    py_path.write_text(render_py(hashes), encoding="utf-8")
