#!/usr/bin/env python3
"""Bake PapyrusLinterCLI SHA-256 digests into the editor plugins.

The plugins download the CLI that matches their own release tag. The hashes
of those binaries are only known after the `release` job uploads them, so
this script is run in the plugin packaging jobs against the just-published
assets and rewrites the checked-in hash modules before vsce/zip run.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

ASSETS = (
    "PapyrusLinterCLI-linux",
    "PapyrusLinterCLI-macos",
    "PapyrusLinterCLI-windows.exe",
)

REPO_ROOT = Path(__file__).resolve().parents[2]
TS_PATH = REPO_ROOT / "vscode-extension" / "src" / "cliHashes.ts"
PY_PATH = REPO_ROOT / "SublimeLinter-contrib-papyrus-lint" / "cli_hashes.py"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def collect_hashes(asset_dir: Path) -> dict[str, str]:
    hashes: dict[str, str] = {}
    missing = []
    for asset in ASSETS:
        path = asset_dir / asset
        if not path.is_file():
            missing.append(asset)
            continue
        hashes[asset] = sha256_file(path)
    if missing:
        raise FileNotFoundError("missing CLI assets: " + ", ".join(missing))
    return hashes


def render_ts(hashes: dict[str, str]) -> str:
    entries = ",\n".join(f"  '{asset}': '{hashes[asset]}'" for asset in ASSETS)
    return (
        "/** SHA-256 digests of this release's PapyrusLinterCLI assets.\n"
        " * Generated by .github/scripts/write_cli_hashes.py; do not edit by hand.\n"
        " */\n"
        "export const CLI_SHA256: Record<string, string> = {\n"
        f"{entries},\n"
        "};\n"
    )


def render_py(hashes: dict[str, str]) -> str:
    entries = ",\n".join(f"    '{asset}': '{hashes[asset]}'" for asset in ASSETS)
    return (
        '"""SHA-256 digests of this release\'s PapyrusLinterCLI assets.\n'
        "\n"
        "Generated by .github/scripts/write_cli_hashes.py; do not edit by hand.\n"
        '"""\n'
        "\n"
        "CLI_SHA256 = {\n"
        f"{entries},\n"
        "}\n"
    )


def write_hashes(hashes: dict[str, str], ts_path: Path = TS_PATH, py_path: Path = PY_PATH) -> None:
    ts_path.parent.mkdir(parents=True, exist_ok=True)
    py_path.parent.mkdir(parents=True, exist_ok=True)
    ts_path.write_text(render_ts(hashes), encoding="utf-8")
    py_path.write_text(render_py(hashes), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("asset_dir", type=Path, help="directory containing the three PapyrusLinterCLI assets")
    parser.add_argument("--ts-path", type=Path, default=TS_PATH)
    parser.add_argument("--py-path", type=Path, default=PY_PATH)
    args = parser.parse_args()
    hashes = collect_hashes(args.asset_dir)
    write_hashes(hashes, args.ts_path, args.py_path)
    print(f"Wrote CLI SHA-256 digests to {args.ts_path} and {args.py_path}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
