//! Flags a `RegisterFor*` call when the script declares no matching
//! `Event` (`OnUpdate` / `OnUpdateGameTime`).
//!
//! Pairs come from `UPDATE_EVENT_PAIRS` (generated by `build.rs`). An AST
//! visitor sees both the call and the event declaration. Scripts that do
//! not parse are left unchecked.
//!
//! Disabled by default: a parent script may declare the handler.

use papyrus_parser::ast::{Expr, FunctionDecl, Script};

use crate::visitor::{AstLint, LintVisitor, Store, VisitCtx};
use crate::Diagnostic;

pub struct UpdateEventPairRule {
    pub register: &'static str,
    pub event: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/update_event_pairs_data.rs"));

/// This lint's [`Diagnostic::rule`] id, for `@disable` line comments.
pub const RULE: &str = "missing-update-handler";

#[derive(Default)]
struct Collect {
    store: Store,
    events: Vec<String>,
}

impl AstLint for Collect {
    fn store(&mut self) -> &mut Store {
        &mut self.store
    }

    fn visit_script(&mut self, script: &Script, ctx: &mut VisitCtx<'_>) {
        self.events.clear();
        collect_events(script, &mut self.events);
        walk_script_calls(script, ctx.config.game, &self.events, &mut self.store);
    }
}

fn collect_events(script: &Script, events: &mut Vec<String>) {
    for function in &script.functions {
        push_event(function, events);
    }
    for state in &script.states {
        for function in &state.functions {
            push_event(function, events);
        }
    }
}

fn push_event(function: &FunctionDecl, events: &mut Vec<String>) {
    if function.is_event {
        events.push(function.name.clone());
    }
}

fn walk_script_calls(
    script: &Script,
    game: crate::Game,
    events: &[String],
    store: &mut Store,
) {
    for function in &script.functions {
        walk_function_calls(function, game, events, store);
    }
    for state in &script.states {
        for function in &state.functions {
            walk_function_calls(function, game, events, store);
        }
    }
    for property in script
        .properties
        .iter()
        .chain(script.groups.iter().flat_map(|group| group.properties.iter()))
    {
        for accessor in &property.accessors {
            walk_function_calls(accessor, game, events, store);
        }
    }
}

fn walk_function_calls(
    function: &FunctionDecl,
    game: crate::Game,
    events: &[String],
    store: &mut Store,
) {
    papyrus_parser::visit::walk_function(
        &mut CallFinder {
            game,
            events,
            store,
        },
        function,
    );
}

struct CallFinder<'a> {
    game: crate::Game,
    events: &'a [String],
    store: &'a mut Store,
}

impl papyrus_parser::visit::Visitor for CallFinder<'_> {
    fn visit_expr(&mut self, expr: &Expr) {
        if let Expr::Call {
            callee,
            line,
            col,
            ..
        } = expr
        {
            if let Some(name) = call_name(callee) {
                if let Some(rule) = find_rule(name, self.game) {
                    if !self
                        .events
                        .iter()
                        .any(|event| event.eq_ignore_ascii_case(rule.event))
                    {
                        let column = col.saturating_sub(name.len()).max(1);
                        self.store.emit(
                            *line,
                            column,
                            format!(
                                "[warning] {name}(...) registers for updates, but this script declares no \
                                 Event {}() to receive them; the registration has no effect",
                                rule.event
                            ),
                            RULE,
                        );
                    }
                }
            }
        }
        papyrus_parser::visit::walk_expr(self, expr);
    }
}

fn call_name(callee: &Expr) -> Option<&str> {
    match callee {
        Expr::Identifier(name) => Some(name),
        Expr::Member { property, .. } => Some(property),
        _ => None,
    }
}

pub fn visitor() -> LintVisitor {
    LintVisitor::Ast(Box::new(Collect::default()))
}

/// Checks `source` for a `RegisterFor*` call with no matching `Event`
/// declared anywhere in the same script.
#[allow(dead_code)] // unit tests; collect_diagnostics uses visitor()
pub fn check(
    source: &str,
    ast: Option<&papyrus_parser::ast::Script>,
    tokens: Option<&[papyrus_parser::token::Token]>,
    config: &crate::config::Config,
    external: &mut impl crate::external_signatures::ExternalSignatures,
) -> Vec<Diagnostic> {
    crate::visitor::run(visitor(), source, ast, tokens, config, external)
}

fn find_rule(name: &str, game: crate::Game) -> Option<&'static UpdateEventPairRule> {
    update_event_pairs_for(game)
        .iter()
        .find(|rule| rule.register.eq_ignore_ascii_case(name))
}

#[cfg(test)]
#[path = "missing_update_handler_tests.rs"]
mod tests;
