//! Single table of built-in lints.
//!
//! Adding a source-level rule should mean: a new module and a
//! `shared/rules.json` entry (`repair_order` if [`apply_repairs`] should
//! auto-fix it). `build.rs` generates the `mod` in `lib.rs` from that
//! entry. Every source-level `check` is
//! `check(source, ast, tokens, config, external)` and every `apply_repairs`
//! fix is `repair(source, ast, tokens, config)`. Source-level dispatch
//! registers enabled ast/tokens rules onto the walkers, walks both trees
//! once, and drains each visitor's [`crate::visitor::Store`] (`none` rules
//! still run `check` directly). [`Rules`],
//! [`default_rules`], [`collect_diagnostics`], [`apply_repairs`],
//! [`KNOWN_RULE_IDS`], and [`FIXABLE_RULE_IDS`] are generated by `build.rs`.

use crate::config::Config;
use crate::external_signatures::ExternalSignatures;

/// Project-level ids that are not dispatched inside this crate. Callers
/// pass matching diagnostics in as `extra_diagnostics`. Only used by this
/// module's own `extra_rule_ids_are_all_known` test; kept as a named
/// constant for documentation.
#[allow(dead_code)]
pub const EXTRA_RULE_IDS: &[&str] = &[
    "conflicting-script-versions",
    "stale-compiled-output",
    "script-filename-mismatch",
];

// `KNOWN_RULE_IDS` (every rule id [`crate::lint`] can report) and
// `FIXABLE_RULE_IDS` (the ones with an automatic fix), both in
// `shared/rules.json`'s own order. Generated by `build.rs` from that file —
// do not edit by hand.
include!(concat!(env!("OUT_DIR"), "/known_rule_ids_data.rs"));

include!(concat!(env!("OUT_DIR"), "/rules_dispatch.rs"));

fn apply_rule(source: String, enabled: bool, repair: impl FnOnce(&str) -> String) -> String {
    if enabled {
        repair(&source)
    } else {
        source
    }
}

#[cfg(test)]
#[path = "registry_tests.rs"]
mod tests;
