//! Single table of built-in lints.
//!
//! Adding a source-level rule should mean: a new module, one entry in
//! [`collect_diagnostics`] (and [`apply_repairs`] if it has a fix), the
//! matching [`crate::config::Rules`] field + default, and a
//! `docs/rules.json` entry. [`KNOWN_RULE_IDS`] / [`FIXABLE_RULE_IDS`] are
//! generated by `build.rs` from `docs/rules.json`, which is the single
//! source of truth for a rule's id/tags/severity/fixability — see "Docs
//! sync" in AGENTS.md.

use crate::argument_types::ExternalSignatures;
use crate::config::{Config, Rules};
use crate::{
    actor_value, argument_naming, argument_override_types, argument_types, array_bounds,
    array_size_range, assignment_operator_spacing, chain_whitespace, circular_dependency,
    comma_spacing, cyclomatic_complexity, debug_side_effects, default_property_value,
    division_by_zero, empty_body, event_signature, exclamation_spacing, explicit_return,
    float_equality, float_int_conversion, forbidden_functions, formid_hex_notation,
    function_override, get_form_from_file_skyrim_esm, get_state_comparison,
    global_variable_increment, global_variable_setvalue, goto_state, identifier_casing,
    impossible_cast, indentation, int_division_to_float, invalid_random_range,
    invariant_loop_condition, local_variable_shadowing, magic_numbers, missing_doc_comment,
    missing_update_handler, named_arguments, native_function_usage, non_global_function_call,
    none_form_usage, numeric_comparison, operator_spacing, parameter_reassignment,
    property_sorting, readonly_property_write, repeated_getvalue, repeated_setoutfit, return_types,
    script_name_collision, self_assignment, semicolon, setvalue_in_loop, short_wait_interval,
    slow_functions, state_count, state_function_signature, static_condition,
    static_function_call_via_instance, strict_boolean, trailing_whitespace, type_casing,
    unchecked_array_element, unchecked_cast, unchecked_form_parameter, unguarded_self_recursion,
    unnecessary_function, unreachable_elseif, unreachable_statement, unresolved_script,
    unused_getter, unused_import, unused_local_variable, unused_property, useless_downcast,
    variable_used_before_assignment, Diagnostic,
};

/// Project-level ids that are not dispatched inside this crate. Callers
/// pass matching diagnostics in as `extra_diagnostics`. Only used by this
/// module's own `extra_rule_ids_are_all_known` test; kept as a named
/// constant for documentation.
#[allow(dead_code)]
pub const EXTRA_RULE_IDS: &[&str] = &[
    "conflicting-script-versions",
    "stale-compiled-output",
    "script-filename-mismatch",
];

// `KNOWN_RULE_IDS` (every rule id [`crate::lint`] can report) and
// `FIXABLE_RULE_IDS` (the ones with an automatic fix), both in
// `docs/rules.json`'s own order. Generated by `build.rs` from that file —
// do not edit by hand.
include!(concat!(env!("OUT_DIR"), "/known_rule_ids_data.rs"));

/// Default enable/disable flags for [`Rules`]. Kept next to the dispatch
/// table so a new field is added in one crate module.
pub fn default_rules() -> Rules {
    Rules {
        trailing_whitespace: true,
        comma_spacing: true,
        forbidden_functions: true,
        formid_hex_notation: true,
        get_form_from_file_skyrim_esm: true,
        slow_functions: true,
        unused_getter: true,
        unused_property: true,
        semicolon: true,
        float_int_conversion: true,
        int_division_to_float: true,
        strict_boolean: true,
        argument_types: true,
        return_types: true,
        function_override: true,
        argument_naming: true,
        argument_override_types: true,
        numeric_comparison: true,
        indentation: true,
        cyclomatic_complexity: true,
        unreachable_statement: true,
        static_condition: true,
        unreachable_elseif: true,
        division_by_zero: true,
        empty_body: true,
        unused_local_variable: true,
        variable_used_before_assignment: true,
        none_form_usage: true,
        local_variable_shadowing: true,
        parameter_reassignment: true,
        chain_whitespace: true,
        exclamation_spacing: true,
        identifier_casing: true,
        type_casing: true,
        named_arguments: true,
        operator_spacing: true,
        assignment_operator_spacing: true,
        property_sorting: false,
        explicit_return: true,
        unchecked_form_parameter: false,
        unchecked_array_element: false,
        unchecked_cast: true,
        useless_downcast: true,
        impossible_cast: true,
        unresolved_script: true,
        non_global_function_call: true,
        static_function_call_via_instance: true,
        short_wait_interval: true,
        state_function_signature: true,
        goto_state: true,
        get_state_comparison: true,
        too_many_states: true,
        multiple_auto_states: true,
        conflicting_script_versions: true,
        stale_compiled_output: true,
        script_filename_mismatch: true,
        unused_disable: false,
        magic_numbers: false,
        native_function_usage: false,
        repeated_getvalue: false,
        global_variable_setvalue: false,
        global_variable_increment: true,
        setvalue_in_loop: true,
        invariant_loop_condition: true,
        script_name_collision: true,
        array_bounds: true,
        array_size_range: true,
        readonly_property_write: true,
        default_property_value: false,
        unguarded_self_recursion: true,
        self_assignment: true,
        debug_side_effects: true,
        unnecessary_function: true,
        unknown_actor_value: false,
        repeated_setoutfit: true,
        missing_doc_comment: false,
        invalid_random_range: true,
        float_equality: false,
        missing_update_handler: false,
        unused_import: true,
        event_signature_mismatch: false,
        circular_dependency: false,
    }
}

pub fn collect_diagnostics<E: ExternalSignatures>(
    source: &str,
    config: &Config,
    external: &mut E,
) -> Vec<Diagnostic> {
    let rules = &config.rules;
    let mut diagnostics = Vec::new();
    collect_token_diagnostics(source, config, rules, &mut diagnostics);
    collect_signature_diagnostics(source, rules, external, &mut diagnostics);
    collect_control_flow_diagnostics(source, config, rules, &mut diagnostics);
    collect_spacing_diagnostics(source, config, rules, &mut diagnostics);
    collect_cast_and_state_diagnostics(source, config, rules, external, &mut diagnostics);
    collect_script_shape_diagnostics(source, rules, &mut diagnostics);
    collect_remaining_diagnostics(source, rules, external, &mut diagnostics);
    diagnostics
}

fn collect_token_diagnostics(
    source: &str,
    config: &Config,
    rules: &Rules,
    diagnostics: &mut Vec<Diagnostic>,
) {
    if rules.trailing_whitespace {
        diagnostics.extend(trailing_whitespace::check(source));
    }
    if rules.comma_spacing {
        diagnostics.extend(comma_spacing::check(source));
    }
    if rules.forbidden_functions {
        diagnostics.extend(forbidden_functions::check(source));
    }
    if rules.slow_functions {
        diagnostics.extend(slow_functions::check(source));
    }
    if rules.formid_hex_notation {
        diagnostics.extend(formid_hex_notation::check(source));
    }
    if rules.get_form_from_file_skyrim_esm {
        diagnostics.extend(get_form_from_file_skyrim_esm::check(source));
    }
    if rules.unused_getter {
        diagnostics.extend(unused_getter::check(source));
    }
    if rules.float_int_conversion {
        diagnostics.extend(float_int_conversion::check(source));
    }
    if rules.int_division_to_float {
        diagnostics.extend(int_division_to_float::check(source));
    }
    if rules.unused_property {
        diagnostics.extend(unused_property::check(source));
    }
    if rules.strict_boolean {
        diagnostics.extend(strict_boolean::check(source, config.bool_like_int));
    }
    if rules.numeric_comparison {
        diagnostics.extend(numeric_comparison::check(source));
    }
    if rules.semicolon {
        diagnostics.extend(semicolon::check(source, config.semicolon_style()));
    }
    if rules.indentation {
        diagnostics.extend(indentation::check(source, config.indentation_unit()));
    }
}

fn collect_signature_diagnostics<E: ExternalSignatures>(
    source: &str,
    rules: &Rules,
    external: &mut E,
    diagnostics: &mut Vec<Diagnostic>,
) {
    if rules.argument_types {
        diagnostics.extend(argument_types::check_with(source, external));
    }
    if rules.return_types {
        diagnostics.extend(return_types::check_with(source, external));
    }
    if rules.unresolved_script {
        diagnostics.extend(unresolved_script::check_with(source, external));
    }
    if rules.non_global_function_call {
        diagnostics.extend(non_global_function_call::check_with(source, external));
    }
    if rules.static_function_call_via_instance {
        diagnostics.extend(static_function_call_via_instance::check_with(
            source, external,
        ));
    }
    if rules.local_variable_shadowing {
        diagnostics.extend(local_variable_shadowing::check_with(source, external));
    }
    if rules.parameter_reassignment {
        diagnostics.extend(parameter_reassignment::check(source));
    }
    if rules.function_override {
        diagnostics.extend(function_override::check_with(source, external));
    }
    if rules.argument_naming {
        diagnostics.extend(argument_naming::check_with(source, external));
    }
    if rules.argument_override_types {
        diagnostics.extend(argument_override_types::check_with(source, external));
    }
    if rules.state_function_signature {
        diagnostics.extend(state_function_signature::check(source));
    }
}

fn collect_control_flow_diagnostics(
    source: &str,
    config: &Config,
    rules: &Rules,
    diagnostics: &mut Vec<Diagnostic>,
) {
    if rules.cyclomatic_complexity {
        diagnostics.extend(cyclomatic_complexity::check(
            source,
            config.cyclomatic_complexity_warning,
            config.cyclomatic_complexity_error,
        ));
    }
    if rules.unreachable_statement {
        diagnostics.extend(unreachable_statement::check(source));
    }
    if rules.static_condition {
        diagnostics.extend(static_condition::check(source));
    }
    if rules.unreachable_elseif {
        diagnostics.extend(unreachable_elseif::check(source));
    }
    if rules.division_by_zero {
        diagnostics.extend(division_by_zero::check(source));
    }
    if rules.invalid_random_range {
        diagnostics.extend(invalid_random_range::check(source));
    }
    if rules.empty_body {
        diagnostics.extend(empty_body::check(source));
    }
    if rules.unused_local_variable {
        diagnostics.extend(unused_local_variable::check(source));
    }
    if rules.variable_used_before_assignment {
        diagnostics.extend(variable_used_before_assignment::check(source));
    }
    if rules.none_form_usage {
        diagnostics.extend(none_form_usage::check(
            source,
            config.assume_auto_properties_filled,
        ));
    }
}

fn collect_spacing_diagnostics(
    source: &str,
    config: &Config,
    rules: &Rules,
    diagnostics: &mut Vec<Diagnostic>,
) {
    if rules.chain_whitespace {
        diagnostics.extend(chain_whitespace::check(source));
    }
    if rules.exclamation_spacing {
        diagnostics.extend(exclamation_spacing::check(source));
    }
    if rules.operator_spacing {
        diagnostics.extend(operator_spacing::check(source));
    }
    if rules.assignment_operator_spacing {
        diagnostics.extend(assignment_operator_spacing::check(source));
    }
    if rules.named_arguments {
        diagnostics.extend(named_arguments::check(source, config.named_arguments));
    }
    if rules.identifier_casing {
        diagnostics.extend(identifier_casing::check(source, config.identifier_casing));
    }
    if rules.type_casing {
        diagnostics.extend(type_casing::check(source, config.type_casing));
    }
    if rules.property_sorting {
        diagnostics.extend(property_sorting::check(source));
    }
    if rules.explicit_return {
        diagnostics.extend(explicit_return::check(source));
    }
}

fn collect_cast_and_state_diagnostics<E: ExternalSignatures>(
    source: &str,
    config: &Config,
    rules: &Rules,
    external: &mut E,
    diagnostics: &mut Vec<Diagnostic>,
) {
    if rules.unchecked_form_parameter {
        diagnostics.extend(unchecked_form_parameter::check(source));
    }
    if rules.unchecked_array_element {
        diagnostics.extend(unchecked_array_element::check(source));
    }
    if rules.unchecked_cast {
        diagnostics.extend(unchecked_cast::check(source));
    }
    if rules.useless_downcast {
        diagnostics.extend(useless_downcast::check_with(source, external));
    }
    if rules.impossible_cast {
        diagnostics.extend(impossible_cast::check_with(source, external));
    }
    if rules.short_wait_interval {
        diagnostics.extend(short_wait_interval::check(source, config.min_wait_interval));
    }
    if rules.goto_state {
        diagnostics.extend(goto_state::check_with(source, external));
    }
    if rules.get_state_comparison {
        diagnostics.extend(get_state_comparison::check_with(source, external));
    }
    if rules.too_many_states {
        diagnostics.extend(state_count::check_too_many_states_with(source, external));
    }
    if rules.multiple_auto_states {
        diagnostics.extend(state_count::check_multiple_auto_states_with(
            source, external,
        ));
    }
    if rules.magic_numbers {
        diagnostics.extend(magic_numbers::check(source, config.magic_numbers));
    }
    if rules.native_function_usage {
        diagnostics.extend(native_function_usage::check(source));
    }
    if rules.repeated_getvalue {
        diagnostics.extend(repeated_getvalue::check(source));
    }
}

fn collect_script_shape_diagnostics(
    source: &str,
    rules: &Rules,
    diagnostics: &mut Vec<Diagnostic>,
) {
    if rules.global_variable_setvalue {
        diagnostics.extend(global_variable_setvalue::check(source));
    }
    if rules.global_variable_increment {
        diagnostics.extend(global_variable_increment::check(source));
    }
    if rules.setvalue_in_loop {
        diagnostics.extend(setvalue_in_loop::check(source));
    }
    if rules.invariant_loop_condition {
        diagnostics.extend(invariant_loop_condition::check(source));
    }
    if rules.script_name_collision {
        diagnostics.extend(script_name_collision::check(source));
    }
    if rules.array_bounds {
        diagnostics.extend(array_bounds::check(source));
    }
    if rules.array_size_range {
        diagnostics.extend(array_size_range::check(source));
    }
    if rules.readonly_property_write {
        diagnostics.extend(readonly_property_write::check(source));
    }
    if rules.default_property_value {
        diagnostics.extend(default_property_value::check(source));
    }
    if rules.unguarded_self_recursion {
        diagnostics.extend(unguarded_self_recursion::check(source));
    }
}

fn collect_remaining_diagnostics<E: ExternalSignatures>(
    source: &str,
    rules: &Rules,
    external: &mut E,
    diagnostics: &mut Vec<Diagnostic>,
) {
    if rules.self_assignment {
        diagnostics.extend(self_assignment::check(source));
    }
    if rules.debug_side_effects {
        diagnostics.extend(debug_side_effects::check(source));
    }
    if rules.unnecessary_function {
        diagnostics.extend(unnecessary_function::check(source));
    }
    if rules.unknown_actor_value {
        diagnostics.extend(actor_value::check(source));
    }
    if rules.repeated_setoutfit {
        diagnostics.extend(repeated_setoutfit::check(source));
    }
    if rules.missing_doc_comment {
        diagnostics.extend(missing_doc_comment::check(source));
    }
    if rules.float_equality {
        diagnostics.extend(float_equality::check(source));
    }
    if rules.missing_update_handler {
        diagnostics.extend(missing_update_handler::check(source));
    }
    if rules.unused_import {
        diagnostics.extend(unused_import::check_with(source, external));
    }
    if rules.event_signature_mismatch {
        diagnostics.extend(event_signature::check(source));
    }
    if rules.circular_dependency {
        diagnostics.extend(circular_dependency::check_with(source, external));
    }
}

pub fn apply_repairs(source: &str, config: &Config, applies: impl Fn(&str) -> bool) -> String {
    let rules = &config.rules;
    let source = apply_style_repairs(source.to_string(), rules, config, &applies);
    let source = apply_spacing_repairs(source, rules, &applies);
    apply_remaining_repairs(source, rules, config, &applies)
}

fn apply_style_repairs(
    source: String,
    rules: &Rules,
    config: &Config,
    applies: &impl Fn(&str) -> bool,
) -> String {
    let source = apply_rule(
        source,
        rules.identifier_casing && applies(identifier_casing::RULE),
        |s| identifier_casing::repair(s, config.identifier_casing),
    );
    let source = apply_rule(
        source,
        rules.slow_functions && applies(slow_functions::RULE),
        slow_functions::repair,
    );
    let source = apply_rule(source, rules.semicolon && applies(semicolon::RULE), |s| {
        semicolon::repair(s, config.semicolon_style())
    });
    let source = apply_rule(
        source,
        rules.indentation && applies(indentation::RULE),
        |s| indentation::repair(s, config.indentation_unit()),
    );
    apply_rule(
        source,
        rules.property_sorting && applies(property_sorting::RULE),
        property_sorting::repair,
    )
}

fn apply_spacing_repairs(source: String, rules: &Rules, applies: &impl Fn(&str) -> bool) -> String {
    let source = apply_rule(
        source,
        rules.comma_spacing && applies(comma_spacing::RULE),
        comma_spacing::repair,
    );
    let source = apply_rule(
        source,
        rules.chain_whitespace && applies(chain_whitespace::RULE),
        chain_whitespace::repair,
    );
    let source = apply_rule(
        source,
        rules.exclamation_spacing && applies(exclamation_spacing::RULE),
        exclamation_spacing::repair,
    );
    let source = apply_rule(
        source,
        rules.operator_spacing && applies(operator_spacing::RULE),
        operator_spacing::repair,
    );
    apply_rule(
        source,
        rules.assignment_operator_spacing && applies(assignment_operator_spacing::RULE),
        assignment_operator_spacing::repair,
    )
}

fn apply_remaining_repairs(
    source: String,
    rules: &Rules,
    config: &Config,
    applies: &impl Fn(&str) -> bool,
) -> String {
    let source = apply_rule(
        source,
        rules.type_casing && applies(type_casing::RULE),
        |s| type_casing::repair(s, config.type_casing),
    );
    let source = apply_rule(
        source,
        rules.trailing_whitespace && applies(trailing_whitespace::RULE),
        trailing_whitespace::repair,
    );
    let source = apply_rule(
        source,
        rules.global_variable_increment && applies(global_variable_increment::RULE),
        global_variable_increment::repair,
    );
    let source = apply_rule(
        source,
        rules.named_arguments && applies(named_arguments::RULE),
        |s| named_arguments::repair(s, config.named_arguments),
    );
    let source = apply_rule(
        source,
        rules.unnecessary_function && applies(unnecessary_function::RULE),
        unnecessary_function::repair,
    );
    let source = apply_rule(
        source,
        rules.formid_hex_notation && applies(formid_hex_notation::RULE),
        formid_hex_notation::repair,
    );
    apply_rule(
        source,
        rules.get_form_from_file_skyrim_esm && applies(get_form_from_file_skyrim_esm::RULE),
        get_form_from_file_skyrim_esm::repair,
    )
}

fn apply_rule(source: String, enabled: bool, repair: impl FnOnce(&str) -> String) -> String {
    if enabled {
        repair(&source)
    } else {
        source
    }
}

#[cfg(test)]
#[path = "registry_tests.rs"]
mod tests;
