use super::*;
use crate::config::Rules;

#[test]
fn extra_rule_ids_are_all_known() {
    for id in EXTRA_RULE_IDS {
        assert!(
            KNOWN_RULE_IDS.contains(id),
            "{id:?} is in EXTRA_RULE_IDS but missing from shared/rules.json"
        );
    }
}

#[test]
fn generated_rules_have_one_field_per_known_id() {
    let value = serde_json::to_value(Rules::default()).expect("Rules serializes");
    let object = value.as_object().expect("Rules serializes as an object");
    assert_eq!(
        object.len(),
        KNOWN_RULE_IDS.len(),
        "Rules fields and shared/rules.json must stay 1:1"
    );
}

/// Cross-checks [`Rules::default`] (generated by `build.rs` from
/// `shared/rules.json`'s `enabled_by_default`) against that same source
/// file, read directly here. This is deliberately data-driven rather than
/// a per-rule hardcoded list: it exercises the id -> `Rules` field
/// generation itself, so it keeps passing as rules are added, removed, or
/// have their default flipped in `shared/rules/<id>.json`, and only fails
/// if the generated default actually stops matching its own source data.
#[test]
fn rule_defaults_match_shared_rules_json() {
    #[derive(serde::Deserialize)]
    struct RuleEntry {
        id: String,
        #[serde(default = "default_true")]
        enabled_by_default: bool,
    }
    fn default_true() -> bool {
        true
    }

    // Mirrors build_support::metadata::RULE_ID_TO_CONFIG_KEY (not
    // reachable from here: build_support is only compiled into build.rs,
    // not this crate) — the handful of rule ids whose `Rules` field name
    // isn't just the id with `-` replaced by `_`.
    const RULE_ID_TO_CONFIG_KEY: &[(&str, &str)] = &[
        ("float-to-int", "float_int_conversion"),
        ("too-many-named-states", "too_many_states"),
    ];

    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../shared/rules.json");
    let contents = std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "failed to read {}: {err} (run .github/scripts/build_rules_json.py first)",
            path.display()
        )
    });
    let rules: Vec<RuleEntry> = serde_json::from_str(&contents)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()));

    let defaults = serde_json::to_value(Rules::default()).expect("Rules serializes");
    let defaults = defaults.as_object().expect("Rules serializes as an object");

    for rule in &rules {
        let config_key = RULE_ID_TO_CONFIG_KEY
            .iter()
            .find(|(id, _)| *id == rule.id)
            .map_or_else(|| rule.id.replace('-', "_"), |(_, key)| (*key).to_string());
        let actual = defaults
            .get(&config_key)
            .and_then(serde_json::Value::as_bool)
            .unwrap_or_else(|| {
                panic!(
                    "Rules has no bool field `{config_key}` for id `{}`",
                    rule.id
                )
            });
        assert_eq!(
            actual, rule.enabled_by_default,
            "Rules::default().{config_key} doesn't match `{}`'s enabled_by_default in shared/rules.json",
            rule.id
        );
    }
}
