//! Metadata tags for every rule in [`crate::KNOWN_RULE_IDS`]: the kind(s) of
//! fix its findings represent (e.g. `"style"`, `"performance"`,
//! `"correctness"`, `"maintainability"`), how important addressing them is
//! to keeping a codebase maintainable, whether they're auto-fixable, and a
//! detailed description of the rule. [`RULE_TAGS`] itself is generated by
//! `build.rs` from `docs/rules.json` (the `definition`/`doc_slug`/`tags`/
//! `importance` fields), which is the single source of truth for this data
//! — see "Docs sync" in AGENTS.md. `docs/nexuspage.bbcode`'s lint tables
//! are generated from `docs/rules.json` too, separately. This module only
//! exposes that metadata; [`crate::repair_filtered_by_tag`] and the CLI's
//! `--tag <kind>` flag are what actually filter lints/fixes down to one
//! kind at a time, built on top of it.

use crate::FIXABLE_RULE_IDS;

/// How important fixing a rule's findings is to keeping a codebase
/// maintainable over time. Independent of the `[error]`/`[warning]`/`[info]`
/// level(s) a rule's own diagnostics carry, which instead reflect runtime
/// risk.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Importance {
    Low,
    Medium,
    High,
}

/// The papyrus-lint website's own base URL, from which every rule's
/// [`RuleTags::doc_url`] is built.
pub const WEBSITE_URL: &str = "https://papyrus-lint.idrinth.de";

/// Tags describing one rule, keyed by its [`Diagnostic::rule`](crate::Diagnostic::rule) id.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleTags {
    pub rule: &'static str,
    /// The anchor id (`pages/build.py`'s `lint-<slugify(name)>`, from that
    /// rule's row in README.md's Implemented Lints tables) this rule's row
    /// renders under on the project website's homepage, so
    /// [`RuleTags::doc_url`] can link straight to it. Generated from
    /// `docs/rules.json`'s `doc_slug` field — see "Docs sync" in AGENTS.md —
    /// since it's derived from the README row's own display name rather
    /// than this rule's id, and the two don't always match (e.g.
    /// `comma-spacing`'s row is titled "Space after comma", slugifying to
    /// `space-after-comma`).
    pub doc_slug: &'static str,
    /// The rule's detailed description, generated from `docs/rules.json`'s
    /// `definition` field, so a consumer (e.g. the desktop app's "Export
    /// for AI" document) can surface the same explanation the README gives
    /// a human reader without needing that documentation on hand.
    pub description: &'static str,
    /// Keyword(s) describing the kind(s) of fix this rule's findings
    /// represent. Never empty.
    pub kinds: &'static [&'static str],
    pub importance: Importance,
}

impl RuleTags {
    /// Whether this rule has an automatic fix. Derived from
    /// [`crate::FIXABLE_RULE_IDS`] rather than stored on each entry here, so
    /// the two can never drift out of sync.
    pub fn auto_fixable(&self) -> bool {
        FIXABLE_RULE_IDS.contains(&self.rule)
    }

    /// The URL of this rule's own row on the project website's homepage
    /// (`<website>/#lint-<doc_slug>`), for a consumer (the desktop app, the
    /// CLI's plain-text/JSON/AI output, the VS Code extension, the
    /// SublimeLinter plugin) to link a finding straight to its
    /// documentation instead of just naming the rule.
    pub fn doc_url(&self) -> String {
        format!("{WEBSITE_URL}/#lint-{}", self.doc_slug)
    }
}

/// Looks up a rule's [`RuleTags`] by its id, matched case-insensitively (the
/// same convention `@disable` directives are matched against — see
/// `disable_comments`). Returns `None` for an id not in
/// [`crate::KNOWN_RULE_IDS`].
pub fn tags_for(rule: &str) -> Option<&'static RuleTags> {
    RULE_TAGS
        .iter()
        .find(|tags| tags.rule.eq_ignore_ascii_case(rule))
}

// One entry per id in [`crate::KNOWN_RULE_IDS`], in the same order.
// Generated by `build.rs` from `docs/rules.json`. Do not edit by hand.
include!(concat!(env!("OUT_DIR"), "/rule_tags_data.rs"));

#[cfg(test)]
mod tests {
    use super::*;
    use crate::KNOWN_RULE_IDS;
    use std::collections::HashSet;

    #[test]
    fn every_known_rule_id_has_tags() {
        for rule in KNOWN_RULE_IDS {
            assert!(
                tags_for(rule).is_some(),
                "{rule:?} is in KNOWN_RULE_IDS but has no RULE_TAGS entry"
            );
        }
    }

    #[test]
    fn every_tagged_rule_is_a_known_rule_id() {
        for tags in RULE_TAGS {
            assert!(
                KNOWN_RULE_IDS.contains(&tags.rule),
                "{:?} has a RULE_TAGS entry but isn't in KNOWN_RULE_IDS",
                tags.rule
            );
        }
    }

    #[test]
    fn rule_tags_has_no_duplicate_rule_ids() {
        let mut seen = HashSet::new();
        for tags in RULE_TAGS {
            assert!(
                seen.insert(tags.rule),
                "{:?} appears more than once in RULE_TAGS",
                tags.rule
            );
        }
    }

    #[test]
    fn every_rule_has_at_least_one_kind() {
        for tags in RULE_TAGS {
            assert!(
                !tags.kinds.is_empty(),
                "{:?} has no kind keywords",
                tags.rule
            );
        }
    }

    #[test]
    fn every_rule_has_a_description() {
        for tags in RULE_TAGS {
            assert!(
                !tags.description.is_empty(),
                "{:?} has no description",
                tags.rule
            );
        }
    }

    #[test]
    fn auto_fixable_matches_fixable_rule_ids() {
        for tags in RULE_TAGS {
            assert_eq!(
                tags.auto_fixable(),
                FIXABLE_RULE_IDS.contains(&tags.rule),
                "{:?}.auto_fixable() disagrees with FIXABLE_RULE_IDS",
                tags.rule
            );
        }
    }

    #[test]
    fn tags_for_matches_case_insensitively() {
        assert_eq!(
            tags_for("TRAILING-WHITESPACE").map(|t| t.rule),
            Some(crate::trailing_whitespace::RULE)
        );
    }

    #[test]
    fn tags_for_returns_none_for_an_unknown_rule() {
        assert!(tags_for("made-up-rule").is_none());
    }

    #[test]
    fn every_rule_has_a_doc_slug_shaped_like_an_html_anchor_fragment() {
        for tags in RULE_TAGS {
            assert!(
                !tags.doc_slug.is_empty()
                    && tags
                        .doc_slug
                        .chars()
                        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
                    && !tags.doc_slug.starts_with('-')
                    && !tags.doc_slug.ends_with('-'),
                "{:?} has an invalid doc_slug {:?}",
                tags.rule,
                tags.doc_slug
            );
        }
    }

    #[test]
    fn rule_tags_has_no_duplicate_doc_slugs() {
        let mut seen = HashSet::new();
        for tags in RULE_TAGS {
            assert!(
                seen.insert(tags.doc_slug),
                "{:?} shares its doc_slug {:?} with another rule",
                tags.rule,
                tags.doc_slug
            );
        }
    }

    #[test]
    fn doc_url_links_to_the_website_lint_anchor() {
        let tags = tags_for(crate::trailing_whitespace::RULE).unwrap();
        assert_eq!(
            tags.doc_url(),
            "https://papyrus-lint.idrinth.de/#lint-trailing-whitespace"
        );
    }
}
