[package]
name = "papyrus-lints"
version = "0.1.0"
description = "Lint rules for Bethesda's Papyrus scripting language"
authors = ["Idrinth"]
edition = "2021"
build = "build.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
papyrus-parser = { path = "../papyrus-parser" }

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

[dev-dependencies]
serde_json = "1"
