name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        issue_message: "Thank you for helping to improve this tool. I'll get to your issue asap, usually within a day."
        pr_message: "Thank you for proposing a change. I'll have a look as soon as possible. That usually means within 24h."
