name: SonarCloud analysis

on:
  push:
    branches: [ "the-one" ]
  pull_request:
    branches: [ "the-one" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v6.0.0
        with:
          java-version: 21
          java-package: jre
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Idrinth_papyrus-lint
            -Dsonar.organization=idrinth-1
          projectBaseDir: .
